print('                  ')
print('    . .   . .     ')
print('   .   . .   .    ')
print('   .    .    .    ')
print('    .  M+I  .    ')
print('     .     .    ')
print('      .   .    ')
print('       . .    ')
print('        .    ')
